### ISSUE TITLE
Create plugin to monitor backup status / last backup using Custom Attributes

### ISSUE THREAD

**Issue by atc0005** [atc0005/check-vmware#506]
### Discussed in https://github.com/atc0005/check-vmware/discussions/504

<div type='discussions-op-text'>

<sup>Originally posted by **tubby1981** November  8, 2021</sup>
At the overview of a VM you have a heading "Custom Attributes" with 2 fields. Namely "Backup status" and "Last backup" In these fields the backup software stores the time when the last successful backup was and information about the backup such as backup job etc. Is it possible to make a nagios check of this as well?

* Warning: If these fields are empty, the VM is not yet included in the backup software
* Critical: if the VM has not been backed up for X number of days
* also an option to exclude vms </div>

## TODO

- [x] GH-590
- [x] documentation updates
  - [x] provide table mapping common date/time input strings to expected layout strings
- [x] contrib files
- [x] remove references to allow ignoring missing custom attributes (dropped feature)
- [x] lowercase `Custom Attributes` in output (official docs don't Title case or headline case this term)
- [x] update default date/time layout string to match example date/time pattern in original plugin request
- [x] replace "backup date" warning/critical terms with "backup age"
- [x] refine vm listings to better handle cases where no backups are present

**Comment by atc0005** [comment]
> * Warning: If these fields are empty, the VM is not yet included in the backup software

Perhaps provide a flag to allow sysadmins to optionally ignore (without WARNING) any VM without values in the specified custom attribute(s). 

As proposed, triggering a WARNING state for VMs without the values seems like a good default.

**Comment by atc0005** [comment]
Cross-post from https://github.com/atc0005/check-vmware/issues/512#issuecomment-969224866:

> @tubby1981: our backup software is commvault.
> 
> Found this topic about this
> https://community.commvault.com/technical-q-a-2/vmware-backup-job-status-output-via-custom-attributes-1796

**Comment by tubby1981** [comment]
any update about this? This plugin would help us a lot.

**Comment by atc0005** [comment]
> any update about this? This plugin would help us a lot.

Thanks for the interest, but nothing yet. I will let you know as soon as I have something to test.

**Comment by atc0005** [comment]
> > * Warning: If these fields are empty, the VM is not yet included in the backup software
> 
> Perhaps provide a flag to allow sysadmins to optionally ignore (without WARNING) any VM without values in the specified custom attribute(s).
> 
> As proposed, triggering a WARNING state for VMs without the values seems like a good default.

Thinking about this now, I'm not sure that this would accomplish anything that excluding VMs by name already does; excluding by name is a feature already supported by other applicable plugins in this project.

Once a functioning plugin is available I can revisit this idea.

**Comment by atc0005** [comment]
Additional "thinking out loud" below (trying to get away from keeping so many local/paper notes).

---

> At the overview of a VM you have a heading "Custom Attributes" with 2 fields. Namely "Backup status" and "Last backup" In these fields the backup software stores the time when the last successful backup was and information about the backup such as backup job etc. Is it possible to make a nagios check of this as well?
> 
> * Warning: If these fields are empty, the VM is not yet included in the backup software
> * Critical: if the VM has not been backed up for X number of days
> * also an option to exclude vms

The goal is to provide the desired behavior, but in a more generic fashion that allows the plugin to be used for more cases than just Commvault backups. The challenge will be to allow general use without either limiting support or making the plugin more difficult to use.

- the plugin would offer a flag to specify a metadata/info custom attribute (`Backup Status` in this case) whose value would be intended primarily for informational output (`LongServiceOutput`)
  - state change if the field is missing
  - all VMs are implicitly evaluated unless explicitly excluded (via VM name or Resource Pool name)
  - VMs could optionally be explicitly *included*, which would implicitly exclude other VMs
    - this behavior is used by other plugins (e.g., `check_vmware_tools`) and is planned for the initial release of this plugin
- the plugin would offer a flag to specify a date field
  - trigger a state change if the threshold is crossed
  - trigger a state change if missing (see earlier notes re implicit/explicit inclusion/exclusion behavior)

Since the scope of the support does not include additional fields, the initial implementation should probably limit the user-specified Custom Attributes to two values. Since the plugin is focused on backups, the flag names should match this focus.

Perhaps ...

- `--backup-metadata-ca`
- `--backup-date-ca`

Not a big fan of the `--backup` prefix as the plugin name will imply that purpose.

Perhaps ...

- `metadata-ca` or `metadata-custom-attribute`
- `date-ca` or `data-custom-attribute`

Maybe both, one as a short flag and the other as the more verbose/self-documenting long flag?

**Comment by atc0005** [comment]
> * the plugin would offer a flag to specify a date field

Perhaps also offer a flag to accept a custom date layout. The default would use the `YYYY-MM-DD HH:MM:SS aa` (where `aa` is either `AM` or `PM`) format (Go layout of `2006-01-02 3:04:05 PM`), but any valid `time.Format` compatible layout would work.

Quick mock-up of the time/date parsing:

```golang
package main

import (
	"fmt"
	"time"
)

func main() {
	timeLayout := "2006-01-02 3:04:05 PM"
	timeString := "2021-11-09 9:07:21 PM"
	result, err := time.Parse(timeLayout, timeString)
	if err != nil {
		fmt.Printf(
			"failed to parse string %q as valid time layout: %v",
			timeString,
			err,
		)
	}
	fmt.Printf("parsed %q as %v\n", timeString, result.Format(time.RFC3339))
}
```

**Comment by atc0005** [comment]
> Perhaps also offer a flag to accept a custom date layout. The default would use the `YYYY-MM-DD HH:MM:SS aa` (where `aa` is either `AM` or `PM`) format (Go layout of `2006-01-02 3:04:05 PM`), but any valid `time.Format` compatible layout would work.
> 
> Quick mock-up of the time/date parsing:

The mock-up uses `time.Parse()`, which defaults to assuming UTC as the time zone when parsing the formatted string.

This plugin may also need to accept a flag value indicating the desired location name corresponding to entries in the `IANA Time Zone` database (e.g., `America/New_York`).

It looks like Go 1.15 (and newer) provide an embedded tzdata package:

- https://go.dev/doc/go1.15#time/tzdata
- https://stackoverflow.com/questions/52489347/how-to-create-a-binary-that-contains-zoneinfo-zip

This can be used to workaround some systems not providing a copy of the timezone database (e.g., containers). Not sure how relevant that is here as Nagios (and similar) monitoring systems are likely to provide a copy of the timezone database. 

Said another way, I don't know if embedding the tzdata package is needed to reliably validate a user specified time zone & parse a recorded `Last Backup` Custom Attribute value.

**Comment by atc0005** [comment]
Thinking out loud:

Should the metadata custom attribute we optional? The current prototype I'm working with assumes it is present and unless a flag is used to ignore missing CAs the plugin will object if it is not.

Perhaps the plugin should use it to emit additional details if it is, but allow not specifying it?

**Comment by atc0005** [comment]
> Perhaps the plugin should use it to emit additional details if it is, but allow not specifying it?

Going this direction.

**Comment by atc0005** [comment]
> Perhaps provide a flag to allow sysadmins to optionally ignore (without WARNING) any VM without values in the specified custom attribute(s).

Going away from this direction. I can't find a solid use case where ignoring a missing backup date wouldn't be better handled by ignoring the VM itself (which is already supported); ignoring a missing backup date seems to nullify the purpose of the plugin?

**Comment by atc0005** [comment]
Bulk of work is in per #590.

TODO:

- documentation updates
- contrib files
- ?

**Comment by atc0005** [comment]
> Bulk of work is in per #590.
> 
> TODO:
> 
> - documentation updates
> - contrib files
> - ?

Another item: remove references to allow ignoring missing custom attributes.
I saw in the shared log details that the alpha.2 version of the plugin is tracking that (non-existent) choice.

https://github.com/atc0005/check-vmware/discussions/504#discussioncomment-1985807

**Comment by atc0005** [comment]
Documentation updates complete (first solid pass anyway).

Further changes are being considered/discussed on #504, so not closing this issue just yet.

**Comment by atc0005** [comment]
Considering this work complete. Further changes can be tracked on later issues.
