### ISSUE TITLE
Add support for excluding/ignoring VMs by `Folder` Managed Object ID (MOID)

### ISSUE THREAD

**Issue by atc0005** [atc0005/check-vmware#809]
## Overview

~Ran into a situation where I needed to filter VMs by `Folder` name.~

Ran into a situation where I needed to filter VMs by a specific `Folder`. While we could attempt to match a name, we could easily run into a situation where the same name is used in multiple places all visible to the same service account. Due to this and because the vSphere Client (web) exposes `Folder` Managed Object ID (MOID) values in the URL we can offer support for filtering by `Folder` MOID values instead.

This could be used in the same way that excluding/including resource pools are currently supported.

## TODO

- [ ] contrib file updates
- [x] plugin documentation refresh
  - [x] add metric descriptions
  - [x] add coverage for new metrics
  - [x] add coverage for new flags

## References

- `Folder` Managed Object Type
  - https://vdc-repo.vmware.com/vmwb-repository/dcr-public/97e6db01-d441-472e-ad53-b48c2bb0e1e4/45347fb1-052d-44b7-b3e9-cbefc34488e3/SDK/vsphere-ws/docs/ReferenceGuide/vim.Folder.html

**Comment by atc0005** [comment]
After giving this some thought, it's probably not a good idea to try to match on a Folder name. Instead, we should filter by a `Folder` MOID value as we can be reasonably confident that we'll be dealing with a single valid match (vs names which could be reused in different Folder hierarchies).

**Comment by atc0005** [comment]
Worth noting (from https://vdc-repo.vmware.com/vmwb-repository/dcr-public/97e6db01-d441-472e-ad53-b48c2bb0e1e4/45347fb1-052d-44b7-b3e9-cbefc34488e3/SDK/vsphere-ws/docs/ReferenceGuide/vim.Folder.html):

> A folder can contain child objects of type `ChildType`. Virtual machine and network entity folders can also contain additional object types. The root folder is a data center folder.

**Comment by atc0005** [comment]
The initial implementation of this feature is complete and applicable plugins have been updated to use the new support:

- `check_vmware_disk_consolidation`
- `check_vmware_hs2ds2vms`
- `check_vmware_question`
- `check_vmware_rps_memory`
- `check_vmware_snapshots_age`
- `check_vmware_snapshots_count`
- `check_vmware_snapshots_size`
- `check_vmware_tools`
- `check_vmware_vcpus`
- `check_vmware_vhw`
- `check_vmware_vm_backup_via_ca`
- `check_vmware_vm_list`
- `check_vmware_vm_power_uptime`

Will test for a bit to make sure nothing obvious is busted before cleaning up/merging to `development` and cutting a pre-release. Aiming for next week.
